# Generated by Django 6.0.6 on 2026-09-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('safety_score', models.FloatField(default=7.0, help_text='Predicted safety score (0.0 to 10.0)')),
                ('last_scored_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_scored_at'],
            },
        ),
    ]
