# Generated by Django 6.0.6 on 2026-09-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='aadhaar_image',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/aadhaar/'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='ai_assessment_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='ai_checks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='ai_outcome',
            field=models.CharField(blank=True, choices=[('forward_for_approval', 'Forward for Approval'), ('manual_review', 'Manual Review'), ('auto_reject', 'Auto Reject')], max_length=30),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='ai_reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='ocr_aadhaar_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='ocr_dob',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='ocr_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='ocr_pan_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='pan_image',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/pan/'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='selfie_image',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/selfies/'),
        ),
    ]
