# Generated by Django 6.0.6 on 2026-09-24 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_verificationrequest_aadhaar_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='consent_data_processing',
            field=models.BooleanField(default=True, help_text='Explicit user consent for identity verification, safety checks, and minimal data processing'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/id_docs/'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('voter_id', 'Voter ID Card'), ('passport', 'Passport'), ('driving_license', 'Driving License')], default='aadhaar', max_length=30),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='reverification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='aadhaar_document_ref',
            field=models.CharField(blank=True, help_text='Secure verification token / masked identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Verified'), ('rejected', 'Rejected'), ('reverification_required', 'Re-verification Required')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='PolicePortalAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_badge_id', models.CharField(blank=True, max_length=100)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('access_purpose', models.TextField(help_text='Official investigative or emergency response purpose')),
                ('data_scope', models.CharField(default='Minimised Verification & Contact Record', max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_portal_accesses', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_access_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SafetyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_responsibility', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=5, help_text='Q1: I believe everyone has a responsibility to help a person facing a genuine emergency.')),
                ('q2_willingness', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=5, help_text='Q2: I would be willing to help someone in an emergency situation when it is safe for me to do so.')),
                ('q3_shared_safety', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=5, help_text="Q3: Women's safety should be treated as a shared responsibility of the entire community.")),
                ('q4_consent_boundaries', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=5, help_text='Q4: I believe respecting personal boundaries and consent is essential for creating a safe environment.')),
                ('q5_incident_reporting', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=5, help_text='Q5: I would report or seek appropriate help if I witnessed a serious safety incident.')),
                ('q6_emergency_confidence', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=5, help_text='Q6: I feel confident that I know what to do when someone around me needs emergency assistance.')),
                ('safety_awareness_score', models.FloatField(default=85.0)),
                ('community_help_score', models.FloatField(default=85.0)),
                ('womens_safety_score', models.FloatField(default=85.0)),
                ('emergency_response_score', models.FloatField(default=85.0)),
                ('responsible_behavior_score', models.FloatField(default=85.0)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_disclaimer', models.TextField(default='Advisory Signal Notice: This AI assessment summary evaluates orientation indicators based on survey responses. It does NOT diagnose mental health, morality, criminality, or character. Final verification decisions are made strictly by authorized human administrators.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_assessments', to=settings.AUTH_USER_MODEL)),
                ('verification_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_assessments', to='verification.verificationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='verification.verificationrequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
