# Generated by Django 6.0.6 on 2026-09-13 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_rename_assigned_guardian_emergency_assigned_responder'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('college', 'College'), ('company', 'Company'), ('hospital', 'Hospital'), ('ngo', 'NGO'), ('government', 'Government'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrgVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_by_org', models.BooleanField(default=False, help_text='Approved by the organization as a designated responder')),
                ('role_at_org', models.CharField(default='designated_responder', help_text='e.g. security_guard, staff, resident_assistant', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_volunteer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.CreateModel(
            name='OrgResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('dashboard_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('notified', 'Notified'), ('acknowledged', 'Acknowledged'), ('declined', 'Declined'), ('timed_out', 'Timed Out')], default='notified', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_responses', to='organization.organization')),
                ('sos_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_responses', to='emergency.emergency')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='organization.orgvolunteer')),
            ],
            options={
                'ordering': ['-notified_at'],
            },
        ),
    ]
