# Generated by Django 6.0.6 on 2026-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_org_type_orgvolunteer_orgresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cctv_monitored',
            field=models.BooleanField(default=True, help_text='CCTV monitored perimeter'),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='emergency_helpline',
            field=models.CharField(blank=True, default='', help_text='24/7 Security Control Room Hotline', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_safe_haven',
            field=models.BooleanField(default=True, help_text='Designated safe haven / shelter for women in distress'),
        ),
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Campus / facility latitude', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Campus / facility longitude', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='operating_hours',
            field=models.CharField(blank=True, default='24/7 Security Coverage', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='security_guards_count',
            field=models.IntegerField(default=5, help_text='Estimated security guard team size'),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
