# Generated by Django 6.0.6 on 2026-09-13 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency', '0002_rename_assigned_guardian_emergency_assigned_responder'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('112_ERSS', '112 National Emergency (ERSS)'), ('twilio_sms', 'Police Control Room SMS'), ('twilio_call', 'Police Control Room Automated Call')], default='112_ERSS', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('ACKNOWLEDGED', 'Acknowledged by Control Room'), ('FAILED', 'Failed')], default='DISPATCHED', max_length=30)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('sos_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gov_alerts', to='emergency.emergency')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
