# Generated by Django 6.0.6 on 2026-06-24 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('security', 'Security Staff'), ('ngo', 'NGO Member'), ('citizen', 'Verified Citizen')], default='volunteer', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('trust_score', models.FloatField(default=5.0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='guardian_docs/')),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_responses', models.IntegerField(default=0)),
                ('successful_responses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_guardians', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trust_score'],
            },
        ),
    ]
