# Generated by Django 6.0.6 on 2026-09-21 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trustedcontact',
            options={'ordering': ['-is_primary', '-added_at']},
        ),
        migrations.AlterUniqueTogether(
            name='trustedcontact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trustedcontact',
            name='alert_call',
            field=models.BooleanField(default=True, help_text='Receive automated voice call on SOS'),
        ),
        migrations.AddField(
            model_name='trustedcontact',
            name='alert_sms',
            field=models.BooleanField(default=True, help_text='Receive instant SMS on SOS'),
        ),
        migrations.AddField(
            model_name='trustedcontact',
            name='alert_whatsapp',
            field=models.BooleanField(default=True, help_text='Enabled for WhatsApp SOS dispatch'),
        ),
        migrations.AddField(
            model_name='trustedcontact',
            name='can_view_location',
            field=models.BooleanField(default=True, help_text='Can track live GPS during emergency'),
        ),
        migrations.AddField(
            model_name='trustedcontact',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email if external contact', max_length=254),
        ),
        migrations.AddField(
            model_name='trustedcontact',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Priority #1 emergency contact'),
        ),
        migrations.AddField(
            model_name='trustedcontact',
            name='last_tested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last drill ping', null=True),
        ),
        migrations.AddField(
            model_name='trustedcontact',
            name='name',
            field=models.CharField(blank=True, help_text='Name if external contact', max_length=150),
        ),
        migrations.AddField(
            model_name='trustedcontact',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number if external contact', max_length=20),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trusted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='relation',
            field=models.CharField(choices=[('family', 'Family'), ('parent', 'Parent / Guardian'), ('sibling', 'Sister / Brother'), ('spouse', 'Spouse / Partner'), ('friend', 'Friend'), ('colleague', 'Colleague / Coworker'), ('neighbor', 'Neighbor'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
