# Generated by Django 6.0.6 on 2026-09-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_data_consent',
            field=models.BooleanField(default=False, help_text='Opt-in consent for anonymous location data in route safety AI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Normal User'), ('local_resident', 'Local Resident'), ('organization', 'Organization'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
