# Generated by Django 6.0.6 on 2026-09-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_location_data_consent_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Normal User'), ('local_resident', 'Local Resident'), ('organization', 'Organization'), ('police', 'Police / Law Enforcement'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
