# Generated by Django 6.0.6 on 2026-09-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='assigned_guardian',
            new_name='assigned_responder',
        ),
    ]
