# Generated by Django 6.0.6 on 2026-09-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_rename_assigned_guardian_emergency_assigned_responder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACCEPTED', 'Accepted'), ('HELP_REACHED', 'Help Reached'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
