# Generated by Django 6.0.6 on 2026-09-16 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency', '0002_rename_assigned_guardian_emergency_assigned_responder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_source', models.CharField(choices=[('local_resident', 'Local Resident Network'), ('organization', 'Organization Network')], default='local_resident', max_length=30)),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('arrival_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_arrival_detected', models.BooleanField(default=False)),
                ('masked_responder_id', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('arrived', 'Arrived at Scene'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='dispatched', max_length=30)),
                ('police_notified_at', models.DateTimeField(blank=True, null=True)),
                ('police_notification_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_dispatch_records', to=settings.AUTH_USER_MODEL)),
                ('sos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records', to='emergency.emergency')),
            ],
            options={
                'ordering': ['-acknowledged_at'],
                'permissions': [('can_view_responder_identity', 'Can view unmasked responder identity in incident records')],
            },
        ),
        migrations.CreateModel(
            name='IncidentBreadcrumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('distance_to_victim_meters', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('incident_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breadcrumbs', to='incident_records.incidentrecord')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IdentityRevealRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Responder Consent'), ('consented', 'Mutual Consent Granted'), ('declined', 'Declined by Responder')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reveal_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reveal_requests', to=settings.AUTH_USER_MODEL)),
                ('incident_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveal_requests', to='incident_records.incidentrecord')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentRecordAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('access_reason', models.TextField(help_text='Mandatory legal/investigative justification for unmasking responder identity.')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_record_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('incident_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='incident_records.incidentrecord')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
    ]
