# Generated by Django 6.0.6 on 2026-09-13 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_rename_assigned_guardian_emergency_assigned_responder'),
        ('local_residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_resident_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('security', 'Security Staff'), ('ngo', 'NGO Member'), ('citizen', 'Verified Citizen')], default='volunteer', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('trust_score', models.FloatField(default=5.0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='resident_docs/')),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_responses', models.IntegerField(default=0)),
                ('successful_responses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_resident_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_residents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local Resident',
                'verbose_name_plural': 'Local Residents',
                'ordering': ['-trust_score'],
            },
        ),
        migrations.CreateModel(
            name='LocalResidentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('notified', 'Notified'), ('acknowledged', 'Acknowledged'), ('declined', 'Declined'), ('timed_out', 'Timed Out')], default='notified', max_length=20)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='local_residents.localresident')),
                ('sos_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_responses', to='emergency.emergency')),
            ],
            options={
                'ordering': ['-notified_at'],
            },
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
    ]
