# Generated by Django 6.0.6 on 2026-09-21 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_residents', '0002_localresident_localresidentresponse_delete_guardian'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='localresident',
            name='area',
            field=models.CharField(blank=True, default='Central Zone', max_length=150),
        ),
        migrations.AddField(
            model_name='localresident',
            name='badge_title',
            field=models.CharField(blank=True, default='Community Guardian', max_length=100),
        ),
        migrations.AddField(
            model_name='localresident',
            name='city',
            field=models.CharField(blank=True, default='Delhi NCR', max_length=100),
        ),
        migrations.AddField(
            model_name='localresident',
            name='response_time_min',
            field=models.IntegerField(default=3, help_text='Average response time in minutes'),
        ),
        migrations.AddField(
            model_name='localresident',
            name='skills',
            field=models.CharField(blank=True, default='First Aid, Night Watch, Safe Haven Room', max_length=255),
        ),
        migrations.CreateModel(
            name='SafeEscortRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('scheduled_time', models.CharField(default='Immediate', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escort_requests', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_escorts', to='local_residents.localresident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
