# Generated by Django 6.0.6 on 2026-09-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentevent',
            name='event_name',
            field=models.CharField(choices=[('SOS_CREATED', 'SOS Created'), ('RESIDENT_NOTIFIED', 'Local Resident Notified'), ('RESIDENT_ACCEPTED', 'Local Resident Accepted'), ('RESIDENT_MOVING', 'Local Resident Moving'), ('RESIDENT_ARRIVED', 'Local Resident Arrived'), ('ORG_VOLUNTEER_NOTIFIED', 'Org Volunteer Notified'), ('ORG_VOLUNTEER_ACCEPTED', 'Org Volunteer Accepted'), ('GOV_ALERT_DISPATCHED', 'Official Emergency Alert Dispatched'), ('HELP_PROVIDED', 'Help Provided'), ('EMERGENCY_CLOSED', 'Emergency Closed'), ('CONTACT_NOTIFIED', 'Trusted Contact Notified'), ('LOCATION_UPDATED', 'Location Updated'), ('GUARDIAN_NOTIFIED', 'Guardian Notified'), ('GUARDIAN_ACCEPTED', 'Guardian Accepted'), ('GUARDIAN_MOVING', 'Guardian Moving'), ('GUARDIAN_ARRIVED', 'Guardian Arrived')], max_length=50),
        ),
    ]
