# Generated by Django 6.0.6 on 2026-06-24 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('SOS_CREATED', 'SOS Created'), ('GUARDIAN_NOTIFIED', 'Guardian Notified'), ('GUARDIAN_ACCEPTED', 'Guardian Accepted'), ('GUARDIAN_MOVING', 'Guardian Moving'), ('GUARDIAN_ARRIVED', 'Guardian Arrived'), ('HELP_PROVIDED', 'Help Provided'), ('EMERGENCY_CLOSED', 'Emergency Closed'), ('CONTACT_NOTIFIED', 'Trusted Contact Notified'), ('LOCATION_UPDATED', 'Location Updated')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='emergency.emergency')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField()),
                ('response_time_minutes', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='emergency.emergency')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
