# Generated by Django 6.0.6 on 2026-06-24 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_meters', models.IntegerField(default=200)),
                ('risk_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('incident_count', models.IntegerField(default=0)),
                ('report_count', models.IntegerField(default=0)),
                ('last_incident', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('harassment', 'Harassment'), ('theft', 'Theft/Robbery'), ('unsafe_area', 'Unsafe Area'), ('poor_lighting', 'Poor Lighting'), ('no_crowd', 'Isolated Area'), ('accident', 'Accident'), ('suspicious', 'Suspicious Activity'), ('safe', 'Safe Area'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
